name: ✨ Feature Request
description: Suggest a new feature or enhancement for FLAC Detective
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out this form to help us understand your request.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm before submitting
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested
          required: true
        - label: I have checked the documentation to confirm this feature doesn't already exist
          required: true

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: What feature would you like to see? What problem does it solve?
      placeholder: |
        I would like to see...
        This would help with...
        Example: Add a --export-json flag to export analysis results in JSON format
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area does this feature relate to?
      options:
        - Analysis / Detection
        - CLI / User Interface
        - Reporting / Output
        - Performance
        - Other
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: When would you use this feature?
      placeholder: |
        This would be useful when...
        Example scenario: ...
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples (Optional)
      description: Show how the feature would work (code snippets, commands, mockups)
      placeholder: |
        ```bash
        flac-detective --new-feature /path/to/files
        ```

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information (alternatives considered, similar features in other tools, etc.)
      placeholder: Add any other context about the feature request
