name: ❓ Question / Discussion
description: Ask a question or start a discussion about FLAC Detective
title: "[Question]: "
labels: ["question"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Have a question about FLAC Detective? We're here to help!

        **Note**: For detailed discussions, consider using [GitHub Discussions](https://github.com/GuillainM/FLAC_Detective/discussions) instead.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm you've checked these resources first
      options:
        - label: I have read the [documentation](https://flac-detective.readthedocs.io)
          required: true
        - label: I have searched existing issues and discussions
          required: true
        - label: I have checked the [troubleshooting guide](https://github.com/GuillainM/FLAC_Detective/blob/main/DIAGNOSTIC_TROUBLESHOOTING.md)
          required: false

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What is your question about?
      options:
        - Installation / Setup
        - Usage / How-to
        - Understanding Results / Verdicts
        - Python API
        - Performance / Optimization
        - Integration with other tools
        - Algorithm / Technical details
        - Best practices
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: Please ask your question clearly and provide relevant context
      placeholder: |
        What is...?
        How do I...?
        Why does...?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context, code examples, or what you've tried so far
      placeholder: |
        I'm trying to...
        I've looked at...
        I expected...
      render: markdown

  - type: textarea
    id: environment
    attributes:
      label: Environment (if relevant)
      description: Provide environment details if relevant to your question
      placeholder: |
        - OS: Windows 11 / macOS / Linux
        - Python version: 3.11
        - FLAC Detective version: 0.8.0
